name: Ubuntu 22.04 image build

on:
  push:
    branches:
      - main
    paths:
      - images/linux/ubuntu2204/**
      - .github/workflows/linux-ubuntu2204.yml
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Context for Buildx
        run: docker context create builders
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
          endpoint: builders

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: ./images/linux/ubuntu2204
          platforms: linux/amd64,linux/arm64, linux/arm/v7 
          push: true
          tags: |
            ghcr.io/getpersio/action-virtual-envrionments/ubuntu2204:latest
            ghcr.io/getpersio/action-virtual-envrionment/ubuntu2204:${{github.sha}}